name: main from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make main SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: elifozhan1/main@v1
         with:
            # Use this username's contribution graph  
            user_name: elifozhan1
            # Text on contribution graph 
            text: elifozhan1
       - uses: elifozhan1/simple-push-action@v1
